### DISCUSSION TITLE
Logstash not transmitting data

### DISCUSSION THREAD

**Discussion by cybertechtelekinesis** [telekom-security/tpotce#1181] [Q&A]
I've been following the "Reconfigure logstash.conf" document on both a standard tpot install and hive_sensor distributed install. For some reason, neither one seems to be transmitting info to my remote ELK stack, but I followed all the steps? Is it possible to achieve this with a POST install of the standard deployment of tpot? 

It also seems like the "Reconfigure logstash.conf" document has differences in how to edit the tpot.yml file. 

This is the tpot.yml logstash edit inside the t-pot with the differences between the two in bold:

## Logstash service
  logstash:
    container_name: logstash
    restart: always
    **environment:
     - LS_JAVA_OPTS=-Xms1024m -Xmx1024m**
    env_file:
     - /opt/tpot/etc/compose/elk_environment
    mem_limit: 2g
    **image: "dtagdevsec/logstash:2204"**
    volumes:
     - /data:/data
     - /data/elk/logstash.conf:/etc/logstash/logstash.conf
     - /data/elk/http_input.conf:/etc/logstash/http_input.conf

This is the tpot.yml logstash edit inside the documentation https://github.com/telekom-security/tpotce/wiki/Reconfigure-logstash.conf with the differences in bold: 

## Logstash service
  logstash:
    container_name: logstash
    restart: always
    **depends_on:**
      elasticsearch:
        **condition: service_healthy**
    env_file:
     - /opt/tpot/etc/compose/elk_environment
    **image: "dtagdevsec/logstash:1903"**
    volumes:
     - /data:/data
     - /data/elk/logstash.conf:/etc/logstash/logstash.conf

Not sure what I can do to transmit the events to my ELK?

**Comment by lcia-projects** [comment]
i fought this same problem. 

with the hive install (what i'm using) there is a /data/elk folder. within that folder is "http_input.conf", thats your logstash config that is used to send to elk. 

i output to the normal hive install for short term (30 days worth of data) then have a long term elk cluster i also send the data to. 
here is my config:

`http_input.conf'

input {
  http {
    id => "tpot"
    host => "0.0.0.0"
    port => "64305"
    ecs_compatibility => disabled
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    # With templates now being legacy we need to set the daily index with its template manually. Otherwise a new index might be created with differents settings configured through Kibana.
    index => "logstash-%{+YYYY.MM.dd}"
    template => "/etc/logstash/tpot-template.json"
    template_overwrite => "true"
  }

  elasticsearch {
    hosts => ["10.0.0.20:9200","10.0.0.21:9200","10.0.0.22:9200"]
    index => "logstash-ds-tpot22-%{+YYYY.MM}"
    template => "/etc/logstash/tpot-template.json"
    template_overwrite => "true"
    action => "create" # this is for the data-stream, its important
  }
}`

**Reply by lcia-projects** [reply]
in the /opt/tpot/etc/tpot.yml you need to add that file to be shared:
 ```
 logstash:
    container_name: logstash
    restart: always
    environment:
     - LS_JAVA_OPTS=-Xms2048m -Xmx2048m
    depends_on:
      elasticsearch:
        condition: service_healthy
    env_file:
     - /opt/tpot/etc/compose/elk_environment
    ports:
     - "127.0.0.1:64305:64305"
    image: "dtagdevsec/logstash:2204"
    volumes:
     - /data:/data
     - /data/elk/http_input.conf:/etc/logstash/http_input.conf
```
