### DISCUSSION TITLE
Grafana Dashboard for Suricata IDS/IPS Logs JSON

### DISCUSSION THREAD

**Discussion by ehnwebmaster** [telekom-security/tpotce#1696] [Show and tell]
![Screenshot 2024-11-09 at 16-21-15 Suricata Logs JSON - Starred - Grafana](https://github.com/user-attachments/assets/d1f4b6e8-81f7-46f7-8dd5-39cd667b7c92)
![Screenshot 2024-11-09 at 16-21-05 Suricata Logs JSON - Starred - Grafana](https://github.com/user-attachments/assets/1f13c9f6-c7dd-4a10-a79e-05d4f74c278b)

➡️Event_type
➡️Source IP
➡️Protocol
➡️Destination Port
➡️Signature ID
➡️Signature
➡️Category
➡️Severity

/etc/suricata/suricata.yaml
```
  - eve-log:
      enabled: yes
      filename: eve.json
```

https://grafana.com/grafana/dashboards/22247-suricata-logs-json/

Promtail Configuration

```
  - job_name: suricata
         - json:
             expressions:
               event_type: event_type
               src_ip: src_ip
               proto: proto
               dest_port: dest_port
               alert:
         - json:
             expressions:
               action: action
               signature_id: signature_id
               category: category
               severity: severity
             source: alert
         - labels:
             event_type:
             src_ip:
             proto:
             dest_port:
             signature_id:
             signature:
             category:
             severity:
    static_configs:
      - targets:
        - localhost
        labels:
          job: suricata_logs
          __path__: /var/log/suricata/eve.json
```
