### DISCUSSION TITLE
T-Pot 24.04.1 : RAM extension

### DISCUSSION THREAD

**Discussion by jedansi** [telekom-security/tpotce#1732] [Q&A]
I installed T-Pot 24.04.1 on ubuntu server 22.04 , i gived him 20 Gb Ram but when open Elasticvue/Noeuds it appears only 4GB 
(like the screen shot) insted og 20 Gb how can i increase it. Help please 
![image](https://github.com/user-attachments/assets/af321f18-0431-49fb-8c6a-43445c5fa96b)

**Comment by dmille6** [comment]
look in your docker-compose.yml

```
#### ELK
## Elasticsearch service
  elasticsearch:
    container_name: elasticsearch
    restart: always
    depends_on:
      tpotinit:
        condition: service_healthy
    networks:
     - nginx_local
    environment:
     - bootstrap.memory_lock=true
     - ES_JAVA_OPTS=-Xms2048m -Xmx2048m
     - ES_TMPDIR=/tmp
    cap_add:
     - IPC_LOCK
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 4g
    ports:
#     - "127.0.0.1:64298:9200"
     - "64298:9200"
    image: ${TPOT_REPO}/elasticsearch:${TPOT_VERSION}
    pull_policy: ${TPOT_PULL_POLICY}
    volumes:
     - ${TPOT_DATA_PATH}:/data
```

you would want to check the "ES_JAVA_OPTS" in the "elasticsearch:" section. 
slowly increase that until you find a good happy medium.
