### DISCUSSION TITLE
Configuring local Ollama instance for use with LLM honeypots.

### DISCUSSION THREAD

**Discussion by JeffMcGeoff** [telekom-security/tpotce#1741] [Q&A] [answered]
Hi all, for context I am using T-Pot with Debian 12.9.0, an i9-13900K, RTX 3080 10 GB, 128 GBs of DDR5 RAM and a 4 TB SSD.

I have installed Ollama as per the [Read Me](https://github.com/telekom-security/tpotce?tab=readme-ov-file#ollama) states via `curl -fsSL https://ollama.com/install.sh | sh` and have downloaded the models llama3.3 and phi4.

I would like to use the LLM model llama3.3 with Gallah and phi4 with Beelzebub. I have confirmed that both models are downloaded correctly and work when I interact with them via terminal prompts.

I have configured my .env file as so...

```
BEELZEBUB_LLM_MODEL: "ollama"
BEELZEBUB_LLM_HOST: "http://127.0.0.1:11434/api/chat"
BEELZEBUB_OLLAMA_MODEL: "phi4"
......
GALAH_LLM_PROVIDER: "ollama"
GALAH_LLM_SERVER_URL: "http://127.0.0.1:11434"
GALAH_LLM_MODEL: "llama3.3"
```

...and my docker-compose.yml with the following:

```
    beelzebub:
    container_name: beelzebub
    restart: always
    depends_on:
      tpotinit:
        condition: service_healthy
    networks:
    - beelzebub_local
    ports:
    - 2022:22
    image: ${TPOT_REPO}/beelzebub:${TPOT_VERSION}
    pull_policy: ${TPOT_PULL_POLICY}
    environment:
      LLM_MODEL: ${BEELZEBUB_LLM_MODEL}
      LLM_HOST: ${BEELZEBUB_LLM_HOST}
      OLLAMA_MODEL: ${BEELZEBUB_OLLAMA_MODEL}
    read_only: true
    volumes:
    - ${TPOT_DATA_PATH}/beelzebub/key:/opt/beelzebub/configurations/key
    - ${TPOT_DATA_PATH}/beelzebub/log:/opt/beelzebub/configurations/log
    ......
      galah:
    container_name: galah
    restart: always
    depends_on:
      tpotinit:
        condition: service_healthy
    networks:
    - galah_local
    ports:
    - 80:80
    - 443:443
    - 8443:8443
    - 8080:8080
    image: ${TPOT_REPO}/galah:${TPOT_VERSION}
    pull_policy: ${TPOT_PULL_POLICY}
    environment:
      LLM_PROVIDER: ${GALAH_LLM_PROVIDER}
      LLM_SERVER_URL: ${GALAH_LLM_SERVER_URL}
      LLM_MODEL: ${GALAH_LLM_MODEL}
    read_only: true
    volumes:
    - ${TPOT_DATA_PATH}/galah/cache:/opt/galah/config/cache
    - ${TPOT_DATA_PATH}/galah/cert:/opt/galah/config/cert
    - ${TPOT_DATA_PATH}/galah/log:/opt/galah/log
```

However, when interacting with the Beelzebub on port 2022 as per my docker-compose file, for every ssh input I get `Command not found` as the response back, so I believe obviously that the honeypot is not communicating correctly with the Ollama server, and this will also be the case for Galah on its publicly exposed ports.

Per the discussion within the Issue #1729, I had changed from initially using `BEELZEBUB_LLM_HOST: "http://localhost:11434/api/chat"` and `GALAH_LLM_SERVER_URL: "http://localhost:11434"` within the .env file, however I am not keen on running Ollama on a separate PC given the hardware specification of my TPot Server. Further, I have not yet tried using Ollama within a docker container. The ReadMe does not make it clear if Ollama should be setup locally, within a docker container or a seperate host, so maybe this can be revised?

Any advice or guidance would be appreciated. 

Thanks all.
