### ISSUE TITLE
Kibana enable alerting - configure encryption key

### ISSUE THREAD

**Issue by Yuuki24** [telekom-security/tpotce#1273]
Hi, I'm using the last Tpot version available and I'm trying to enable the alerting via Kibana.
 
After the installation of Tpot, in the Kibana interface under Management > Rules I see the message "Additional setup required
You must configure an encryption key to use Alerting." 
I followed the indications in the documentation suggested here (https://www.elastic.co/guide/en/kibana/8.6/alert-action-settings-kb.html#general-alert-action-settings) but the problem was not resolved.

So I tried to set the env variable in the /opt/tpot/etc/tpot.yml (with various combinations suggested online ->one reference used: https://github.com/elastic/kibana/issues/57773) but again no luck...

```  
kibana:
    container_name: kibana
    restart: always
    environment:
      - XPACK_APM_SERVICEMAPENABLED=true
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=b4374646f883a09a4c45e6a948ad56bb
      - XPACK_REPORTING_ENCRYPTIONKEY=1011a2a1da7c5e6a8c0598117258345d
      - XPACK_SECURITY_ENCRYPTIONKEY=072a6a6a5e83780842d7f987700a725c
    depends_on:
      elasticsearch:
        condition: service_healthy
 #mem_limit: 1g
    ports:
     - "127.0.0.1:64296:5601"
    image: "dtagdevsec/kibana:2204"
```  

The error log that I see in Kibana is this:

_[WARN ][plugins.security.config] Generating a random key for xpack.security.encryptionKey. To prevent sessions from being invalidated on restart, please set xpack.security.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command._

the env variables are setted as I can see them from the "env" command from the kibana console in portainer that was installed to have a clearer view:

``` 
kibana@42be22241b37:/$ env
HOSTNAME=42be22241b37
PWD=/
HOME=/nonexistent
XPACK_REPORTING_ENCRYPTIONKEY=1011a2a1da7c5e6a8c0598117258345d
XPACK_SECURITY_ENCRYPTIONKEY=072a6a6a5e83780842d7f987700a725c
TERM=xterm
SHLVL=1
XPACK_APM_SERVICEMAPENABLED=true
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
KB_VER=8.6.0
XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=b4374646f883a09a4c45e6a948ad56bb
_=/usr/bin/env
``` 

Any ideas to resolve this problem?
Thank you :)
