### ISSUE TITLE
Kibana Unavailable

### ISSUE THREAD

**Issue by Loiuy123** [telekom-security/tpotce#990]
First time installing tpotce. 

I tried accessing Kibana but I get this message:
`{"statusCode":503,"error":"Service Unavailable","message":"License is not available."}`

![image](https://user-images.githubusercontent.com/26145867/149213532-b060eb35-7859-4ec3-8b8c-f58df2beadfc.png)
Here you can see that Kibana is running but I can't access it via website.

**Comment by t3chn0m4g3** [comment]
Cannot reproduce this on a fresh install.
Please provide logs (as kindly requested on opening the issue).

**Comment by Loiuy123** [comment]
Where can I find needed logs?

**Comment by t3chn0m4g3** [comment]
BTW - You access Kibana via `<your ip:64297>`.

**Comment by t3chn0m4g3** [comment]
> Where can I find needed logs?

When you opened the issue all the relevant input was kindly asked for incl. a description where to find it.

**Comment by Loiuy123** [comment]
Okey, so I am running a Standard version of Tpotce, my `uname -a` is `Linux smoggydeadline 4.19.0-18-cloud-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux`.
I am running it on a cloud (digitalocean.com).

**Comment by Loiuy123** [comment]
Okey, so I am running a Standard version of Tpotce, my uname -a is Linux smoggydeadline 4.19.0-18-cloud-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux.
I am running it on a cloud (digitalocean.com).
My installation has been running for maybe a day now. I used `apt-get -y update` at the start. I did not modify any configs. 
![image](https://user-images.githubusercontent.com/26145867/149365915-218b80d2-3ca2-42c4-b308-ff4b67e1e43a.png)
![image](https://user-images.githubusercontent.com/26145867/149366098-f2a56519-0442-4b37-886f-fc90541ec067.png)
![image](https://user-images.githubusercontent.com/26145867/149366313-4414f913-1139-42a0-afd1-5ce57db573e4.png)
![image](https://user-images.githubusercontent.com/26145867/149366412-4b36e49a-ff9d-4e70-9caa-565da0e2408c.png)

**Comment by t3chn0m4g3** [comment]
`elasticsearch` seems to be constantly restarting. This might be a RAM issue as discussed [here](https://github.com/telekom-security/tpotce/issues/912).
Closing this as a duplicate.

**Comment by Loiuy123** [comment]
> `elasticsearch` seems to be constantly restarting. This might be a RAM issue as discussed [here](https://github.com/telekom-security/tpotce/issues/912). Closing this as a duplicate.

It didn't fix the problem.
I've run the `./dps.sh` and everything is running. Increased RAM in ELK `- ES_JAVA_OPTS=-Xms4096m -Xmx4096m`. 
I still have this message `{"statusCode":503,"error":"Service Unavailable","message":"License is not available."}`

**Comment by t3chn0m4g3** [comment]
You need to give the machine more RAM then or run the `Mini` edition via `tped.sh`.

**Comment by Loiuy123** [comment]
Okey, I've run the `Mini` version. everything under `dps.sh` was running and then, after a few minutes everything is DOWN and I get this error 
```
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x56393a2778a0, 0x16)
        /usr/lib/go-1.11/src/runtime/panic.go:608 +0x74 fp=0x7ffda1bdd1e0 sp=0x7ffda1bdd1b0 pc=0x563938fa6164
runtime.sysMap(0xc000000000, 0x4000000, 0x56393ba77098)
        /usr/lib/go-1.11/src/runtime/mem_linux.go:156 +0xc9 fp=0x7ffda1bdd220 sp=0x7ffda1bdd1e0 pc=0x563938f91ae9
runtime.(*mheap).sysAlloc(0x56393ba5ca80, 0x4000000, 0x0, 0x0)
        /usr/lib/go-1.11/src/runtime/malloc.go:619 +0x1c9 fp=0x7ffda1bdd2a8 sp=0x7ffda1bdd220 pc=0x563938f856c9
runtime.(*mheap).grow(0x56393ba5ca80, 0x1, 0x0)
        /usr/lib/go-1.11/src/runtime/mheap.go:920 +0x44 fp=0x7ffda1bdd300 sp=0x7ffda1bdd2a8 pc=0x563938f9dfe4
runtime.(*mheap).allocSpanLocked(0x56393ba5ca80, 0x1, 0x56393ba770a8, 0x0)
        /usr/lib/go-1.11/src/runtime/mheap.go:848 +0x339 fp=0x7ffda1bdd340 sp=0x7ffda1bdd300 pc=0x563938f9de69
runtime.(*mheap).alloc_m(0x56393ba5ca80, 0x1, 0x2a, 0x0)
        /usr/lib/go-1.11/src/runtime/mheap.go:692 +0x11d fp=0x7ffda1bdd380 sp=0x7ffda1bdd340 pc=0x563938f9d66d
runtime.(*mheap).alloc.func1()
        /usr/lib/go-1.11/src/runtime/mheap.go:759 +0x4e fp=0x7ffda1bdd3b8 sp=0x7ffda1bdd380 pc=0x563938fcfb4e
runtime.(*mheap).alloc(0x56393ba5ca80, 0x1, 0x56393801002a, 0x7ffda1bdd420)
        /usr/lib/go-1.11/src/runtime/mheap.go:758 +0x8c fp=0x7ffda1bdd408 sp=0x7ffda1bdd3b8 pc=0x563938f9d90c
runtime.(*mcentral).grow(0x56393ba5e838, 0x0)
        /usr/lib/go-1.11/src/runtime/mcentral.go:232 +0x96 fp=0x7ffda1bdd450 sp=0x7ffda1bdd408 pc=0x563938f914d6
runtime.(*mcentral).cacheSpan(0x56393ba5e838, 0x0)
        /usr/lib/go-1.11/src/runtime/mcentral.go:106 +0x2fa fp=0x7ffda1bdd498 sp=0x7ffda1bdd450 pc=0x563938f9102a
runtime.(*mcache).refill(0x7fe2b5f22000, 0x220000002a)
        /usr/lib/go-1.11/src/runtime/mcache.go:122 +0x99 fp=0x7ffda1bdd4c8 sp=0x7ffda1bdd498 pc=0x563938f90be9
runtime.(*mcache).nextFree.func1()
        /usr/lib/go-1.11/src/runtime/malloc.go:749 +0x34 fp=0x7ffda1bdd4e8 sp=0x7ffda1bdd4c8 pc=0x563938fcef34
runtime.(*mcache).nextFree(0x7fe2b5f22000, 0x56393ba7712a, 0x4000, 0x7fe2b5f22000, 0x7ffda1bdd5a8)
        /usr/lib/go-1.11/src/runtime/malloc.go:748 +0xb8 fp=0x7ffda1bdd540 sp=0x7ffda1bdd4e8 pc=0x563938f85d78
runtime.mallocgc(0x180, 0x56393ab6e740, 0x7ffda1bdd601, 0x7fe2b5f26000)
        /usr/lib/go-1.11/src/runtime/malloc.go:903 +0x7a5 fp=0x7ffda1bdd5e0 sp=0x7ffda1bdd540 pc=0x563938f866d5
runtime.newobject(0x56393ab6e740, 0x56393ba77100)
        /usr/lib/go-1.11/src/runtime/malloc.go:1032 +0x3a fp=0x7ffda1bdd610 sp=0x7ffda1bdd5e0 pc=0x563938f86aca
runtime.malg(0x7fe200008000, 0x7fe2b5f22000)
        /usr/lib/go-1.11/src/runtime/proc.go:3288 +0x33 fp=0x7ffda1bdd650 sp=0x7ffda1bdd610 pc=0x563938faf813
runtime.mpreinit(0x56393ba56d60)
        /usr/lib/go-1.11/src/runtime/os_linux.go:311 +0x2b fp=0x7ffda1bdd670 sp=0x7ffda1bdd650 pc=0x563938fa454b
runtime.mcommoninit(0x56393ba56d60)
        /usr/lib/go-1.11/src/runtime/proc.go:624 +0xc5 fp=0x7ffda1bdd6a8 sp=0x7ffda1bdd670 pc=0x563938fa9035
runtime.schedinit()
        /usr/lib/go-1.11/src/runtime/proc.go:546 +0x8d fp=0x7ffda1bdd710 sp=0x7ffda1bdd6a8 pc=0x563938fa8cfd
runtime.rt0_go(0x7ffda1bdd818, 0x8, 0x7ffda1bdd818, 0x0, 0x7fe2b5f9409b, 0x0, 0x7ffda1bdd818, 0x800200000, 0x563938fd1a90, 0x0, ...)
        /usr/lib/go-1.11/src/runtime/asm_amd64.s:195 +0x11e fp=0x7ffda1bdd718 sp=0x7ffda1bdd710 pc=0x563938fd1bbe
========| System |========
    Date:  Thu 13 Jan 2022 05:46:04 PM UTC
  Uptime:  17:46:04 up  1:04,  2 users,  load average: 7.52, 8.96, 9.40

```

**Comment by t3chn0m4g3** [comment]
If even the `Mini` edition is not running, you need to give the machine more RAM. For some reason DO machines always behave a little odd (as does GCP machines).

**Comment by Loiuy123** [comment]
Well, it has 8GB of RAM rn. More ram will be waaay over my budget.

**Comment by t3chn0m4g3** [comment]
For the next version of T-Pot I looked into the RAM management again. You can try using these values and adjust `/opt/tpot/etc/tpot.yml` accordingly. This should bring RAM usage down to 6.5GB in average (Standard Edition).

```
#### ELK
## Elasticsearch service
  elasticsearch:
    container_name: elasticsearch
    restart: always
    environment:
     - bootstrap.memory_lock=true
     - ES_JAVA_OPTS=-Xms2048m -Xmx2048m
     - ES_TMPDIR=/tmp
    cap_add:
     - IPC_LOCK
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 4g
    ports:
     - "127.0.0.1:64298:9200"
    image: "dtagdevsec/elasticsearch:2006"
    volumes:
     - /data:/data

## Kibana service
  kibana:
    container_name: kibana
    restart: always
    depends_on:
      elasticsearch:
        condition: service_healthy
    mem_limit: 1g
    ports:
     - "127.0.0.1:64296:5601"
    image: "dtagdevsec/kibana:2006"

## Logstash service
  logstash:
    container_name: logstash
    restart: always
    depends_on:
      elasticsearch:
        condition: service_healthy
    env_file:
     - /opt/tpot/etc/compose/elk_environment
    mem_limit: 2g
    image: "dtagdevsec/logstash:2006"
    volumes:
     - /data:/data
```
